export const data = [
  {
    title: "Online Shop",
    technologies: ["html", "css"],
    bgColor: "#fff",
    color: "#000",
    borderColor: "#fff",
    imgUrl: "https://files.fm/thumb_show.php?i=4qt9g49rf",
  },
  {
    title: "Online Shop",
    technologies: ["html", "css"],
    bgColor: "#fff",
    color: "#000",
    borderColor: "#fff",
    imgUrl: "https://files.fm/thumb_show.php?i=4qt9g49rf",
  },
  {
    title: "Online Shop",
    technologies: ["bootstrap", "git"],
    bgColor: "#fff",
    color: "#000",
    borderColor: "#fff",
    imgUrl: "https://files.fm/thumb_show.php?i=4qt9g49rf",
  },
  {
    title: "Online Shop",
    technologies: ["bootstrap", "git"],
    bgColor: "#000",
    color: "#fff",
    borderColor: "#fff",
    imgUrl: "https://files.fm/thumb_show.php?i=4qt9g49rf",
  },
  {
    title: "Online Shop",
    technologies: ["js", "ts"],
    bgColor: "#fff",
    color: "#fff",
    borderColor: "#fff",
    imgUrl: "https://files.fm/thumb_show.php?i=4qt9g49rf",
  },
];
